source 'https://rubygems.org'
ruby '~> 2.2', '>= 2.2.2'

gem 'rake', '~> 13.0.6'
gem 'activerecord', '~> 7.0'
gem 'activesupport', '~> 7.0'
gem 'rspec', '~> 3.5'
gem 'sqlite3', '~> 1.3.13'
gem 'database_cleaner', '~> 1.5.3'
gem 'standalone_migrations'
